/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package maze.gui;

import java.awt.Dimension;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import maze.logic.MazeGame;

/**
 *
 * @author andre
 */
public class HomeOptionsGUI extends javax.swing.JFrame {

    /**
     *
     */
    private static final long serialVersionUID = 1L;

    /**
     * Creates new form HomeOptionsGUI
     */
    public HomeOptionsGUI() {
        initComponents();
        setMinimumSize(new Dimension(400, 390));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jRadioButton3 = new javax.swing.JRadioButton();
        jTextField1 = new javax.swing.JTextField();
        jComboBox1 = new javax.swing.JComboBox();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jTextField5 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Game Options");
        getContentPane().setLayout(null);

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel2.setText("<html>\nMaze Size\n(between 10 and 50):");
        jLabel2.setToolTipText("");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(150, 100, 80, 50);

        jLabel3.setText("Dragons:");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(150, 150, 70, 30);

        jLabel4.setText("Dragons Behaviour:");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(150, 180, 160, 20);

        buttonGroup1.add(jRadioButton1);
        jRadioButton1.setLabel("Frozen");
        jRadioButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jRadioButton1);
        jRadioButton1.setBounds(150, 200, 123, 24);

        buttonGroup1.add(jRadioButton2);
        jRadioButton2.setLabel("Can move");
        jRadioButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jRadioButton2);
        jRadioButton2.setBounds(150, 220, 94, 24);

        buttonGroup1.add(jRadioButton3);
        jRadioButton3.setSelected(true);
        jRadioButton3.setLabel("Can move and sleep");
        getContentPane().add(jRadioButton3);
        jRadioButton3.setBounds(150, 240, 180, 20);

        jTextField1.setText("30");
        getContentPane().add(jTextField1);
        jTextField1.setBounds(230, 110, 80, 30);

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1", "2", "3" }));
        getContentPane().add(jComboBox1);
        jComboBox1.setBounds(230, 160, 56, 28);

        jLabel5.setText("Control Keys:");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(60, 260, 92, 18);

        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("↑");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(70, 280, 10, 20);

        jTextField2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField2.setText("W");
        jTextField2.setToolTipText("");
        getContentPane().add(jTextField2);
        jTextField2.setBounds(90, 280, 30, 30);

        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("←");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(140, 280, 13, 20);

        jTextField3.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField3.setText("A");
        getContentPane().add(jTextField3);
        jTextField3.setBounds(160, 280, 30, 30);

        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("↓");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(206, 280, 10, 20);

        jTextField4.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField4.setText("S");
        getContentPane().add(jTextField4);
        jTextField4.setBounds(230, 280, 30, 30);

        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("→");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(280, 280, 13, 20);

        jTextField5.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField5.setText("D");
        getContentPane().add(jTextField5);
        jTextField5.setBounds(300, 280, 30, 30);

        jButton1.setText("Let's play!");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(90, 320, 220, 30);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/GameOptions.png"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 400, 390);

        pack();
    }// </editor-fold>//GEN-END:initComponents
    int radioButtonSelected = 3;

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        boolean proceed = true;
        if (!jTextField1.getText().isEmpty() && !jTextField2.getText().isEmpty()
                && !jTextField3.getText().isEmpty()
                && !jTextField4.getText().isEmpty()
                && !jTextField5.getText().isEmpty()) {
            int mazeDim = 0;
            try {
                mazeDim = Integer.parseInt(jTextField1.getText());

            } catch (NumberFormatException ex) {
                proceed = false;
            }
            if (proceed) {
                if (mazeDim >= 10 && mazeDim <= 50) {
                    int dragonOp = radioButtonSelected;
                    int nDragons = Integer.parseInt(jComboBox1.getSelectedItem().toString());
                    char moveChars[] = {Character.toUpperCase(jTextField2.getText().charAt(0)),
                        Character.toUpperCase(jTextField3.getText().charAt(0)),
                        Character.toUpperCase(jTextField4.getText().charAt(0)),
                        Character.toUpperCase(jTextField5.getText().charAt(0))};
                    MazeGame.setOptions(mazeDim, dragonOp, nDragons, moveChars);
                    try {
                        MazeGame.startGui();
                    } catch (IOException ex) {
                        Logger.getLogger(HomeOptionsGUI.class.getName()).log(Level.SEVERE, null, ex);
                    }
                    MazeGame.optionsSet = true;
                    this.dispose();
                }
            }
        }

    }//GEN-LAST:event_jButton1ActionPerformed

    private void jRadioButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton1ActionPerformed
        radioButtonSelected = 1;
    }//GEN-LAST:event_jRadioButton1ActionPerformed

    private void jRadioButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton2ActionPerformed
        radioButtonSelected = 2;
    }//GEN-LAST:event_jRadioButton2ActionPerformed
    private void jRadioButton3ActionPerformed(java.awt.event.ActionEvent evt) {
        radioButtonSelected = 3;
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HomeOptionsGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /*
         * Create and display the form
         */
        java.awt.EventQueue.invokeLater(new Runnable() {

            @Override
            public void run() {
                new HomeOptionsGUI().setVisible(true);
            }
        });
    }

    public static void showGui() {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HomeOptionsGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /*
         * Create and display the form
         */
        java.awt.EventQueue.invokeLater(new Runnable() {

            @Override
            public void run() {
                new HomeOptionsGUI().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JRadioButton jRadioButton3;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    // End of variables declaration//GEN-END:variables
}
